# Generated by Django 6.0.2 on 2026-02-28 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='nazwa marki')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='nazwa modelu')),
                ('generation', models.IntegerField(verbose_name='generacja modelu')),
                ('segment', models.CharField(choices=[('A', 'budget'), ('B', 'basic'), ('C', 'compact'), ('D', 'delux'), ('E', 'executive')], verbose_name='segment modelu')),
                ('description', models.TextField(verbose_name='opis modelu')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='reservations.brand')),
            ],
        ),
    ]
