# Generated by Django 6.0.2 on 2026-02-28 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=16, verbose_name='numer rejestracyjny')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='cena za dobe')),
                ('description', models.TextField(verbose_name='opis samochodu')),
                ('mileage', models.PositiveIntegerField(verbose_name='przebieg')),
                ('production_date', models.DateField(verbose_name='data produkcji')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='reservations.model')),
            ],
        ),
    ]
