# Generated by Django 6.0.2 on 2026-03-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_start_date_alter_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='nazwa marki'),
        ),
    ]
